export const MODALIDADES_ESPORTIVAS = [
  // Atletismo
  'Atletismo - 100m Rasos',
  'Atletismo - 200m Rasos',
  'Atletismo - 400m Rasos',
  'Atletismo - 800m',
  'Atletismo - 1500m',
  'Atletismo - 5000m',
  'Atletismo - 10000m',
  'Atletismo - Maratona',
  'Atletismo - 100m com Barreiras',
  'Atletismo - 110m com Barreiras',
  'Atletismo - 400m com Barreiras',
  'Atletismo - 3000m com Obstáculos',
  'Atletismo - Revezamento 4x100m',
  'Atletismo - Revezamento 4x400m',
  'Atletismo - Salto em Altura',
  'Atletismo - Salto com Vara',
  'Atletismo - Salto em Distância',
  'Atletismo - Salto Triplo',
  'Atletismo - Arremesso de Peso',
  'Atletismo - Lançamento de Disco',
  'Atletismo - Lançamento de Martelo',
  'Atletismo - Lançamento de Dardo',
  'Atletismo - Decatlo',
  'Atletismo - Heptatlo',
  'Atletismo - Marcha Atlética 20km',
  'Atletismo - Marcha Atlética 50km',

  // Natação
  'Natação - 50m Livre',
  'Natação - 100m Livre',
  'Natação - 200m Livre',
  'Natação - 400m Livre',
  'Natação - 800m Livre',
  'Natação - 1500m Livre',
  'Natação - 50m Costas',
  'Natação - 100m Costas',
  'Natação - 200m Costas',
  'Natação - 50m Peito',
  'Natação - 100m Peito',
  'Natação - 200m Peito',
  'Natação - 50m Borboleta',
  'Natação - 100m Borboleta',
  'Natação - 200m Borboleta',
  'Natação - 200m Medley',
  'Natação - 400m Medley',
  'Natação - Revezamento 4x100m Livre',
  'Natação - Revezamento 4x200m Livre',
  'Natação - Revezamento 4x100m Medley',
  'Natação - Maratona Aquática 10km',

  // Futebol
  'Futebol - Masculino',
  'Futebol - Feminino',
  'Futebol de Campo - Sub-15',
  'Futebol de Campo - Sub-17',
  'Futebol de Campo - Sub-20',
  'Futebol Society',
  'Futsal - Masculino',
  'Futsal - Feminino',
  'Futebol de Areia - Masculino',
  'Futebol de Areia - Feminino',

  // Vôlei
  'Voleibol - Masculino',
  'Voleibol - Feminino',
  'Voleibol de Praia - Masculino',
  'Voleibol de Praia - Feminino',

  // Basquete
  'Basquetebol - Masculino',
  'Basquetebol - Feminino',
  'Basquete 3x3 - Masculino',
  'Basquete 3x3 - Feminino',

  // Handebol
  'Handebol - Masculino',
  'Handebol - Feminino',
  'Handebol de Areia - Masculino',
  'Handebol de Areia - Feminino',

  // Judô
  'Judô - Masculino até 60kg',
  'Judô - Masculino até 66kg',
  'Judô - Masculino até 73kg',
  'Judô - Masculino até 81kg',
  'Judô - Masculino até 90kg',
  'Judô - Masculino até 100kg',
  'Judô - Masculino acima de 100kg',
  'Judô - Feminino até 48kg',
  'Judô - Feminino até 52kg',
  'Judô - Feminino até 57kg',
  'Judô - Feminino até 63kg',
  'Judô - Feminino até 70kg',
  'Judô - Feminino até 78kg',
  'Judô - Feminino acima de 78kg',

  // Tênis
  'Tênis - Simples Masculino',
  'Tênis - Simples Feminino',
  'Tênis - Duplas Masculinas',
  'Tênis - Duplas Femininas',
  'Tênis - Duplas Mistas',
  'Tênis de Mesa - Simples Masculino',
  'Tênis de Mesa - Simples Feminino',
  'Tênis de Mesa - Duplas Masculinas',
  'Tênis de Mesa - Duplas Femininas',
  'Tênis de Mesa - Duplas Mistas',
  'Tênis de Mesa - Equipes Masculinas',
  'Tênis de Mesa - Equipes Femininas',

  // Ciclismo
  'Ciclismo - Estrada Individual',
  'Ciclismo - Estrada por Equipes',
  'Ciclismo - Contrarelógio',
  'Ciclismo - Mountain Bike',
  'Ciclismo - BMX Racing',
  'Ciclismo - BMX Freestyle',
  'Ciclismo - Pista Velocidade',
  'Ciclismo - Pista Perseguição',
  'Ciclismo - Pista Keirin',

  // Ginástica
  'Ginástica Artística - Solo Masculino',
  'Ginástica Artística - Solo Feminino',
  'Ginástica Artística - Cavalo com Alças',
  'Ginástica Artística - Argolas',
  'Ginástica Artística - Salto Masculino',
  'Ginástica Artística - Salto Feminino',
  'Ginástica Artística - Barras Paralelas',
  'Ginástica Artística - Barra Fixa',
  'Ginástica Artística - Trave',
  'Ginástica Artística - Barras Assimétricas',
  'Ginástica Rítmica - Individual Geral',
  'Ginástica Rítmica - Conjunto',
  'Ginástica de Trampolim',

  // Boxe
  'Boxe - Masculino até 49kg',
  'Boxe - Masculino até 52kg',
  'Boxe - Masculino até 56kg',
  'Boxe - Masculino até 60kg',
  'Boxe - Masculino até 64kg',
  'Boxe - Masculino até 69kg',
  'Boxe - Masculino até 75kg',
  'Boxe - Masculino até 81kg',
  'Boxe - Masculino até 91kg',
  'Boxe - Masculino acima de 91kg',
  'Boxe - Feminino até 50kg',
  'Boxe - Feminino até 54kg',
  'Boxe - Feminino até 57kg',
  'Boxe - Feminino até 60kg',
  'Boxe - Feminino até 66kg',
  'Boxe - Feminino até 75kg',

  // Modalidades Aquáticas
  'Saltos Ornamentais - Trampolim 1m',
  'Saltos Ornamentais - Trampolim 3m',
  'Saltos Ornamentais - Plataforma 10m',
  'Saltos Ornamentais - Sincronizado 3m',
  'Saltos Ornamentais - Sincronizado 10m',
  'Polo Aquático - Masculino',
  'Polo Aquático - Feminino',
  'Nado Sincronizado - Solo',
  'Nado Sincronizado - Dueto',
  'Nado Sincronizado - Equipe',

  // Remo
  'Remo - Skiff Simples Masculino',
  'Remo - Skiff Simples Feminino',
  'Remo - Skiff Duplo Masculino',
  'Remo - Skiff Duplo Feminino',
  'Remo - Dois sem Timoneiro Masculino',
  'Remo - Dois sem Timoneiro Feminino',
  'Remo - Quatro sem Timoneiro Masculino',
  'Remo - Quatro sem Timoneiro Feminino',
  'Remo - Oito com Timoneiro Masculino',
  'Remo - Oito com Timoneiro Feminino',

  // Canoagem
  'Canoagem Velocidade - K1 200m Masculino',
  'Canoagem Velocidade - K1 200m Feminino',
  'Canoagem Velocidade - K1 500m Masculino',
  'Canoagem Velocidade - K1 500m Feminino',
  'Canoagem Velocidade - K1 1000m Masculino',
  'Canoagem Velocidade - C1 200m Masculino',
  'Canoagem Velocidade - C1 1000m Masculino',
  'Canoagem Slalom - K1 Masculino',
  'Canoagem Slalom - K1 Feminino',
  'Canoagem Slalom - C1 Masculino',
  'Canoagem Slalom - C1 Feminino',

  // Modalidades de Combate
  'Taekwondo - Masculino até 58kg',
  'Taekwondo - Masculino até 68kg',
  'Taekwondo - Masculino até 80kg',
  'Taekwondo - Masculino acima de 80kg',
  'Taekwondo - Feminino até 49kg',
  'Taekwondo - Feminino até 57kg',
  'Taekwondo - Feminino até 67kg',
  'Taekwondo - Feminino acima de 67kg',
  'Karatê - Kata Masculino',
  'Karatê - Kata Feminino',
  'Karatê - Kumite Masculino',
  'Karatê - Kumite Feminino',
  'Jiu-Jitsu Brasileiro',
  'MMA - Artes Marciais Mistas',

  // Modalidades com Raquete
  'Badminton - Simples Masculino',
  'Badminton - Simples Feminino',
  'Badminton - Duplas Masculinas',
  'Badminton - Duplas Femininas',
  'Badminton - Duplas Mistas',
  'Squash - Masculino',
  'Squash - Feminino',

  // Tiro
  'Tiro Esportivo - Pistola 10m',
  'Tiro Esportivo - Pistola 25m',
  'Tiro Esportivo - Rifle 10m',
  'Tiro Esportivo - Rifle 50m',
  'Tiro Esportivo - Trap',
  'Tiro Esportivo - Skeet',
  'Tiro com Arco - Individual Masculino',
  'Tiro com Arco - Individual Feminino',
  'Tiro com Arco - Equipes Masculinas',
  'Tiro com Arco - Equipes Femininas',
  'Tiro com Arco - Duplas Mistas',

  // Modalidades de Força
  'Levantamento de Peso - Masculino até 61kg',
  'Levantamento de Peso - Masculino até 67kg',
  'Levantamento de Peso - Masculino até 73kg',
  'Levantamento de Peso - Masculino até 81kg',
  'Levantamento de Peso - Masculino até 96kg',
  'Levantamento de Peso - Masculino até 109kg',
  'Levantamento de Peso - Masculino acima de 109kg',
  'Levantamento de Peso - Feminino até 49kg',
  'Levantamento de Peso - Feminino até 55kg',
  'Levantamento de Peso - Feminino até 59kg',
  'Levantamento de Peso - Feminino até 64kg',
  'Levantamento de Peso - Feminino até 71kg',
  'Levantamento de Peso - Feminino até 76kg',
  'Levantamento de Peso - Feminino acima de 87kg',

  // Modalidades Equestres
  'Hipismo - Saltos Individual',
  'Hipismo - Saltos por Equipes',
  'Hipismo - Adestramento Individual',
  'Hipismo - Adestramento por Equipes',
  'Hipismo - CCE Individual',
  'Hipismo - CCE por Equipes',

  // Modalidades de Aventura
  'Escalada Esportiva - Velocidade',
  'Escalada Esportiva - Boulder',
  'Escalada Esportiva - Dificuldade',
  'Surfe - Masculino',
  'Surfe - Feminino',
  'Skate - Street Masculino',
  'Skate - Street Feminino',
  'Skate - Park Masculino',
  'Skate - Park Feminino',

  // Modalidades Paralímpicas
  'Atletismo Paralímpico',
  'Natação Paralímpica',
  'Basquetebol em Cadeira de Rodas',
  'Tênis em Cadeira de Rodas',
  'Tênis de Mesa Paralímpico',
  'Goalball',
  'Futebol de 5',
  'Futebol de 7',
  'Voleibol Sentado',
  'Rugby em Cadeira de Rodas',
  'Bocha Paralímpica',
  'Halterofilismo Paralímpico',
  'Tiro Paralímpico',
  'Tiro com Arco Paralímpico',
  'Ciclismo Paralímpico',
  'Hipismo Paralímpico',
  'Judô Paralímpico',
  'Esgrima em Cadeira de Rodas',
  'Canoagem Paralímpica',
  'Remo Paralímpico',
  'Triathlon Paralímpico',

  // Modalidades Regionais/Tradicionais
  'Capoeira',
  'Corrida de Orientação',
  'Xadrez',
  'Damas',
  'Dominó',
  'Truco',
  'Peteca',
  'Frescobol',
  'Corrida de Rua',
  'Maratona Aquática',
  'Triathlon',
  'Pentatlo Moderno',
  'Biribol',
  'Futevôlei',
  'Altinha',
  'Crossfit',
];

export const CATEGORIAS_IDADE = [
  'Master 60+ (60 anos ou mais)',
];

export const TIPOS_COMPETICAO = [
  'Eliminatória Simples',
  'Eliminatória Dupla',
  'Liga/Pontos Corridos',
  'Grupos + Mata-mata',
  'Suíço',
  'Round Robin',
  'Tempo/Marca',
  'Melhor de 3',
  'Melhor de 5',
  'Qualificatória + Final',
];

export const STATUS_COMPETICAO = [
  'Planejada',
  'Inscrições Abertas',
  'Em Andamento',
  'Finalizada',
  'Cancelada',
  'Adiada',
];

export const GENEROS = [
  'Masculino',
  'Feminino',
  'Misto',
];